# Generated by Django 5.1.4 on 2025-01-12 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_related_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
