"""
Django settings for djangocha project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4zn-k_z=#c28^g6!i=*w_!81_8v_s)l075-$it56l&&z%&)qm4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'panel_sms',
    'rest_framework',
    'chat',


]
# settings.py

JAZZMIN_SETTINGS = {
    # سایت و برند
    "site_title": "Library Admin",
    "site_header": "Library Management",
    "site_brand": "Library Admin",
    "site_logo": "books/img/logo.png",  # مسیر لوگوی دلخواه
    "site_logo_classes": "img-circle",
    "site_icon": "books/img/favicon.ico",  # آیکون مرورگر
    "welcome_sign": "Welcome to the Library Admin Panel",
    "copyright": "© 2025 Library Inc",
    "language_chooser": True,  # فعال‌سازی انتخاب زبان
    "theme": "green",
    # منوی بالا
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Docs", "url": "https://docs.djangoproject.com/", "new_window": True},
        {"model": "auth.User"},
        {"app": "books"},
    ],

    # منوی کاربر
    "usermenu_links": [
        {"name": "Profile", "url": "/profile", "icon": "fas fa-user-circle"},
        {"name": "Support", "url": "https://support.example.com", "new_window": True, "icon": "fas fa-life-ring"},
    ],

    # منوی جانبی
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    "custom_links": {
        "books": [
            {
                "name": "Generate Report",
                "url": "generate_report",
                "icon": "fas fa-chart-line",
                "permissions": ["books.view_book"]
            },
            {
                "name": "Send Notifications",
                "url": "send_notifications",
                "icon": "fas fa-envelope",
                "permissions": ["books.view_book"]
            }
        ]
    },

    # آیکون‌های اپلیکیشن‌ها و مدل‌ها
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "books": "fas fa-book",
        "books.author": "fas fa-feather-alt",
        "books.book": "fas fa-book-open",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",

    # مدل مرتبط
    "related_modal_active": True,

    # تغییرات UI
    "custom_css": "css/custom_admin.css",  # مسیر فایل CSS دلخواه
    "custom_js": "js/custom_admin.js",    # مسیر فایل JS دلخواه
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # تغییر نمایش فرم‌ها
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "vertical_tabs",
        "auth.group": "collapsible"
    },

    # انتخاب فونت‌ها
    "use_google_fonts_cdn": True,
     
}



MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangocha.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # مسیر پوشه templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# WSGI_APPLICATION = 'djangocha.wsgi.application'

# channels
ASGI_APPLICATION = "djangocha.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGES = [
    ('en', ('English')),
    ('fa', ('فارسی')),  # اضافه کردن زبان فارسی
]

LANGUAGE_CODE = 'en'  # زبان پیش‌فرض فارسی


TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



STATIC_URL = 'static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
